[tool.sqlfluff.core]
templater = "dbt"
sql_file_exts = ".sql,.sql.j2,.dml,.ddl"
dialect = "postgres"

[tool.sqlfluff.templater.dbt]
project_dir = "."
profile = "default"

[tool.sqlfluff.rules]
max_line_length = 120
